# AMPEL360 H₂-BWB-Q Orchestrator Configuration
# Part of the E-EXECUTING pillar

# Execution Configuration
execution:
  max_parallel_workflows: 3
  timeout_minutes: 120
  retry_attempts: 2
  workflow_types:
    - feasible-enumeration
    - risk-aware-selection
    - full-optimization
    - validation-only

# Resource Management
resources:
  classical_backend: cpu
  quantum_backend: qasm_simulator
  max_memory_gb: 16
  max_cpu_cores: 8
  quantum_shots: 1024
  
  # Resource allocation per workflow type
  allocation:
    feasible-enumeration:
      cpu_cores: 4
      memory_gb: 8
      priority: high
    risk-aware-selection:
      cpu_cores: 2
      memory_gb: 4
      quantum_shots: 1024
      priority: medium
    full-optimization:
      cpu_cores: 6
      memory_gb: 12
      quantum_shots: 2048
      priority: high

# Monitoring Configuration
monitoring:
  metrics_collection: true
  log_level: INFO
  health_check_interval: 30
  performance_sampling: 10
  
  # Metrics to track
  metrics:
    - throughput_configs_per_hour
    - latency_seconds
    - resource_utilization_percent
    - success_rate_percent
    - error_rate_percent
    - queue_depth

# Stage Configuration
stages:
  feasible-enumeration:
    enabled: true
    solver: cp-sat
    timeout_minutes: 30
    max_configurations: 1000
    
  risk-aware-selection:
    enabled: true
    optimizer: qaoa
    max_iterations: 100
    cvar_alpha: 0.95
    risk_beta: 0.1
    
  validation:
    enabled: true
    checks:
      - configuration_validity
      - constraint_compliance
      - certification_requirements
      - safety_criteria

# Integration Configuration
integration:
  # Other pillars
  organizational:
    approval_required: true
    governance_endpoint: "O-ORGANIZATIONAL/governance/approval-service"
    
  procedural:
    workflow_compliance: true
    procedure_validation: "P-PROCEDURAL/validation/workflow-checker"
    
  technological:
    component_registry: "T-TECHNOLOGICAL/AMEDEO-PELLICCIA/component-registry"
    utcs_compliance: true
    
  intelligent:
    qaoa_service: "I-INTELLIGENT/scripts/qaoa_over_F.py"
    ai_models: "I-INTELLIGENT/models/"
    
  machine:
    digital_twin: "M-MACHINE/digital-twin/bwb-h2-twin"
    simulation_engine: "M-MACHINE/simulation/"

# Security and Compliance
security:
  encryption_at_rest: true
  encryption_in_transit: true
  audit_logging: true
  access_control: rbac
  
  # Certification compliance
  certification:
    arp4754a: true
    arp4761: true
    do178c: true
    do254: true

# Output Configuration
output:
  base_directory: "results/"
  format: json
  compression: true
  retention_days: 90
  
  # Artifacts to generate
  artifacts:
    - feasible_set.json
    - optimal_config.json
    - deployment_manifest.json
    - execution_log.txt
    - metrics_report.json
    - certification_artifacts.zip

# Error Handling
error_handling:
  retry_on_failure: true
  max_retries: 2
  retry_delay_seconds: 60
  fallback_to_classical: true
  
  # Error categorization
  error_types:
    transient:
      - network_timeout
      - resource_unavailable
      - quantum_backend_busy
    permanent:
      - configuration_invalid
      - constraint_violation
      - certification_failure

# Notification Configuration
notifications:
  enabled: true
  channels:
    - email
    - webhook
    - dashboard
  
  # Notification triggers
  triggers:
    workflow_started: info
    workflow_completed: success
    workflow_failed: error
    resource_exhausted: warning
    certification_issue: critical