pipeline:
  name: "AMPEL360 Deployment Pipeline"
  utcs.phase: ["07-Deployment", "08-Operations"]
  trigger: ["main_branch_push", "release_tag"]

stages:
  - name: "build"
    steps:
      - "docker_build"
      - "security_scan"
      - "artifact_signing"
  
  - name: "test"
    steps:
      - "integration_tests"
      - "performance_tests" 
      - "security_tests"
  
  - name: "staging_deploy"
    steps:
      - "deploy_to_staging"
      - "smoke_tests"
      - "integration_validation"
  
  - name: "production_deploy"
    approval: "required"
    steps:
      - "blue_green_deployment"
      - "health_checks"
      - "rollback_capability"

environments:
  staging:
    cluster: "k8s-staging"
    namespace: "ampel360-staging"
    replicas: 1
    resources:
      cpu: "500m"
      memory: "1Gi"
  
  production:
    cluster: "k8s-prod"
    namespace: "ampel360-prod"
    replicas: 3
    resources:
      cpu: "2000m"
      memory: "4Gi"

quality_gates:
  - "all_tests_pass"
  - "security_scan_clean"
  - "performance_benchmarks_met"
  - "manual_approval_production"

monitoring:
  metrics: ["response_time", "error_rate", "throughput"]
  alerts: ["high_error_rate", "performance_degradation"]
  dashboards: ["deployment_health", "application_metrics"]