# AMPEL360-H2-BWB-QNNN Configuration
# Main configuration file for the AMPEL360 Hydrogen BWB aircraft framework

metadata:
  version: "5.0"
  doc_id: "UTCS-MI/CS25-H2/AMPEL360-QNNN/2025-08-26/v1.0"
  status: "P2-Approved-Pending-QNNN"
  created: "2025-08-26"
  last_updated: "2025-08-26"

program_info:
  name: "AMPEL360 H₂-BWB QNNN"
  type: "Blended Wing Body with Hydrogen Propulsion"
  certification_basis: "CS-25/FAR-25 with H₂ appendices"
  phase: "P2 - Introduce BWB"

architecture:
  methodology: "AMEDEO-PELLICCIA"
  components:
    fuselage: 24        # BWB configuration
    wing: 24            # BWB configuration (alt: 34 if TRL≥6)
    primary_structure: 24
    flight_controls: 24
    propulsion: 37      # H₂ turbofan
    energy: 38          # H₂ BWB rear-mounted
    avionics: 1         # TUW systems (BWB-adapted)
    landing_gear: 1
    cabin: 1
    tail: "N/A-BWB"     # Not applicable for BWB

capacity:
  qnnn: null            # To be determined by optimization
  passenger_range:
    min: 150
    max: 220
  objective: "E[cost] + beta * CVaR_alpha(cost)"

optimization:
  method: "MILP/CP-SAT + QAOA"
  risk_parameters:
    cvar_alpha: 0.8     # Focus on tail risk (80th percentile)
    beta: 0.25          # Risk weight in objective function
  
corridors:
  seed_airports:
    - "LHR"             # London Heathrow
    - "FRA"             # Frankfurt
    - "DXB"             # Dubai
    - "SIN"             # Singapore

constraints:
  trl_gates: true
  compatibility_rules: true
  geometric_validation: true
  certification_compliance: true

paths:
  organizational: "OPTIM-FRAMEWORK/O-ORGANIZATIONAL/"
  procedural: "OPTIM-FRAMEWORK/P-PROCEDURAL/"
  technological: "OPTIM-FRAMEWORK/T-TECHNOLOGICAL/"

notes: |
  - Tail not applicable for BWB configuration
  - If geometry gates fail for TUW gear/avionics/cabin, select BWB-dedicated modules
  - H₂ storage requires specialized cryogenic systems integration
  - BWB configuration enables unique passenger and cargo arrangements